# Generated by Django 5.2.6 on 2026-09-15 15:43

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_enable_pg_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('province_code', models.CharField(blank=True, max_length=2, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_rep', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name', 'company_code'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Lower('name'), name='gin_trgm_ops'), name='company_name_trgm')],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_row_id', models.CharField(max_length=32, unique=True)),
                ('contact_code', models.CharField(max_length=40, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=80, null=True)),
                ('fax', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.company')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'contact_code'],
            },
        ),
        migrations.CreateModel(
            name='FairEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fair_edition_code', models.CharField(max_length=32, unique=True)),
                ('fair_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('venue', models.CharField(max_length=255)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('max_stand_height_m', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ['-starts_on', 'fair_name'],
                'indexes': [models.Index(fields=['starts_on', 'ends_on'], name='fair_dates_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='fair_end_after_start'), models.CheckConstraint(condition=models.Q(('max_stand_height_m__gt', 0)), name='fair_height_positive')],
            },
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_version', models.CharField(max_length=64)),
                ('source_checksums', models.JSONField(default=dict)),
                ('record_counts', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['status'], name='import_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_code', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('client_budget_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sales_status', models.CharField(choices=[('open', 'Open'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('won', 'Won'), ('lost', 'Lost')], max_length=32)),
                ('opened_on', models.DateField()),
                ('expected_close_on', models.DateField(blank=True, null=True)),
                ('historical_campaign_code', models.CharField(blank=True, max_length=100, null=True)),
                ('stand_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requested_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('brief_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.company')),
                ('fair_edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.fairedition')),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_opportunities', to='crm.contact')),
            ],
            options={
                'ordering': ['-opened_on', 'opportunity_code'],
            },
        ),
        migrations.CreateModel(
            name='HandoffRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_snapshot', models.JSONField()),
                ('preparer_output', models.JSONField()),
                ('checker_output', models.JSONField()),
                ('coordinator_decision', models.CharField(choices=[('continue', 'Continue'), ('stop', 'Stop')], max_length=16)),
                ('decision_reason', models.TextField()),
                ('next_action', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoff_runs', to='crm.opportunity')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_entry_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('activity_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('note', 'Note'), ('task', 'Task')], max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('details', models.TextField()),
                ('follow_up_on', models.DateField(blank=True, null=True)),
                ('completion_marker', models.CharField(blank=True, choices=[('Y', 'Completed interaction'), ('N', 'Pending task')], max_length=1, null=True)),
                ('author', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.company')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.opportunity')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Lower('first_name'), name='gin_trgm_ops'), name='contact_first_trgm'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Lower('last_name'), name='gin_trgm_ops'), name='contact_last_trgm'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Lower('email'), name='gin_trgm_ops'), name='contact_email_trgm'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['company', 'fair_edition'], name='opp_company_fair_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['sales_status'], name='opp_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('amount_eur__isnull', True), ('amount_eur__gte', 0), _connector='OR'), name='opp_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('client_budget_eur__isnull', True), ('client_budget_eur__gte', 0), _connector='OR'), name='opp_budget_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('stand_area_sqm__isnull', True), ('stand_area_sqm__gt', 0), _connector='OR'), name='opp_area_positive'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('requested_height_m__isnull', True), ('requested_height_m__gt', 0), _connector='OR'), name='opp_height_positive'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('expected_close_on__isnull', True), ('expected_close_on__gte', models.F('opened_on')), _connector='OR'), name='opp_close_after_open'),
        ),
        migrations.AddIndex(
            model_name='handoffrun',
            index=models.Index(fields=['opportunity', '-created_at'], name='handoff_opp_time_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['opportunity', '-occurred_at'], name='activity_opp_time_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['company', '-occurred_at'], name='activity_company_time_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(condition=models.Q(('follow_up_on__isnull', False)), fields=['follow_up_on'], name='activity_follow_up_idx'),
        ),
    ]
